# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_companies', '0003_auto_20180426_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='human_resources',
            field=models.ManyToManyField(blank=True, related_name='hr_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learningco_companies.Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leader_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
