# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Extract')),
                ('avatar', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('linkedin', models.URLField(blank=True, verbose_name='Linkedin')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('github', models.URLField(blank=True, verbose_name='Github')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
