image: python:3.6

before_script:
  - python --version
  - pip install bandit==1.4.0 radon==2.2.0 flake8==3.3.0

stages:
  - pep8
  - radon
  - bandit

pep8:
  stage: pep8
  script:
    - flake8

radon:
  stage: radon
  script:
    - radon cc .
    - radon mi .

bandit:
  stage: bandit
  script:
    - bandit -r .
