image: python:3.6

services:
  - postgres:9.6
  - redis:3.2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  POSTGRES_DB: learningco

cache:
  paths:
    - .cache/
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r docker/python/requirements.txt

stages:
  - pep8
  - radon
  - bandit
  - coverage
  - test

pep8:
  stage: pep8
  script:
    - flake8

radon:
  stage: radon
  script:
    - radon cc .
    - radon mi .

bandit:
  stage: bandit
  script:
    - bandit -r .

coverage: &app
  stage: coverage
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - python manage.py migrate
    - coverage run --source='.' manage.py test
    - coverage report -m --fail-under=80

test:
  <<: *app
  stage: test
  script:
    - python manage.py test
