# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learningco_content', '0006_bundle'),
        ('learningco_companies', '0005_auto_20180529_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='learningco_companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySkillScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningco_companies.Company')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningco_content.Skill')),
            ],
        ),
    ]
