# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_companies', '0006_auto_20180606_0338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningco_content', '0011_auto_20180709_1743'),
        ('learningco_score', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyskillscore',
            unique_together=set([('company', 'skill')]),
        ),
        migrations.RemoveField(
            model_name='leaderskillscore',
            name='lessons',
        ),
        migrations.AlterUniqueTogether(
            name='leaderskillscore',
            unique_together=set([('leader', 'skill')]),
        ),
    ]
