# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningco_content', '0006_bundle'),
        ('learningco_score', '0002_leaderscore_leaderskillscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderSkillQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningco_content.Skill')),
            ],
        ),
    ]
