# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 04:11
from __future__ import unicode_literals

from django.db import migrations


def trigger_signals(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Skill = apps.get_model(
        'learningco_content', 'Skill')
    Company = apps.get_model(
        'learningco_companies', 'Company')
    User = apps.get_model(
        'auth', 'User')

    for obj in Skill.objects.using(db_alias).all():
        obj.save()

    for obj in Company.objects.using(db_alias).all():
        obj.save()

    for obj in User.objects.using(db_alias).all():
        obj.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_score', '0003_auto_20180712_0411'),
    ]

    operations = [
        migrations.RunPython(
            trigger_signals, do_nothing),
    ]
