# Generated by Django 2.1.2 on 2018-10-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_core', '0001_initial'),
        ('publicomex_teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.Team')),
            ],
            bases=('publicomex_teams.team',),
        ),
        migrations.CreateModel(
            name='RegionalTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.Team')),
                ('zones', models.ManyToManyField(to='publicomex_core.Zone')),
            ],
            bases=('publicomex_teams.team',),
        ),
    ]
