# Generated by Django 2.1.2 on 2018-10-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_teams', '0002_nationalteam_regionalteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('nationalteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.NationalTeam')),
            ],
            bases=('publicomex_teams.nationalteam',),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('nationalteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.NationalTeam')),
            ],
            bases=('publicomex_teams.nationalteam',),
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('nationalteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.NationalTeam')),
            ],
            bases=('publicomex_teams.nationalteam',),
        ),
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('regionalteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.RegionalTeam')),
            ],
            bases=('publicomex_teams.regionalteam',),
        ),
        migrations.CreateModel(
            name='RegionalMarketing',
            fields=[
                ('regionalteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicomex_teams.RegionalTeam')),
            ],
            bases=('publicomex_teams.regionalteam',),
        ),
    ]
