# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('body', models.TextField(default='')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lección',
                'ordering': ['name'],
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sealedair_content.Lesson')),
            ],
            options={
                'verbose_name': 'Leccion',
                'ordering': ['name'],
                'manager_inheritance_from_future': True,
            },
            bases=('sealedair_content.lesson',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sealedair_content.Lesson')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Articulo',
                'ordering': ['name'],
                'manager_inheritance_from_future': True,
            },
            bases=('sealedair_content.lesson',),
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sealedair_content.Lesson')),
            ],
            options={
                'verbose_name': 'Intro',
                'ordering': ['name'],
                'manager_inheritance_from_future': True,
            },
            bases=('sealedair_content.lesson',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sealedair_content.Lesson')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'ordering': ['name'],
                'manager_inheritance_from_future': True,
            },
            bases=('sealedair_content.lesson',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sealedair_content.Lesson')),
                ('video_url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name': 'Video',
                'ordering': ['name'],
                'manager_inheritance_from_future': True,
            },
            bases=('sealedair_content.lesson',),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sealedair_content.Question', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_sealedair_content.lesson_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='sealedair_content.Skill', verbose_name='Competencia'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='lessons',
            field=models.ManyToManyField(to='sealedair_content.Lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sealedair_content.Quiz', verbose_name='Cuestionario'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='activity_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_list_bundles', to='sealedair_content.ActivityList'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_bundles', to='sealedair_content.Article'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='intro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_bundles', to='sealedair_content.Intro'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_bundles', to='sealedair_content.Quiz'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_bundles', to='sealedair_content.Video'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sealedair_content.ActivityList', verbose_name='Lista de actividades'),
        ),
    ]
