# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_content', '0002_auto_20180610_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylist',
            options={'ordering': ['name'], 'verbose_name': 'Actividades'},
        ),
        migrations.AddField(
            model_name='activity',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
