# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_content', '0004_auto_20180629_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='full_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='full_text',
        ),
    ]
