# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_content', '0005_auto_20180703_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='activity_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_list_skills', to='sealedair_content.ActivityList'),
        ),
        migrations.AddField(
            model_name='skill',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_skills', to='sealedair_content.Article'),
        ),
        migrations.AddField(
            model_name='skill',
            name='intro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_skills', to='sealedair_content.Intro'),
        ),
        migrations.AddField(
            model_name='skill',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_skills', to='sealedair_content.Quiz'),
        ),
        migrations.AddField(
            model_name='skill',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_skills', to='sealedair_content.Video'),
        ),
    ]
