# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_content', '0008_auto_20180709_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='default',
        ),
    ]
