# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_users', '0003_auto_20180529_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level_of_hierarchy',
            field=models.CharField(choices=[('TLM', 'Directivo'), ('MLM', 'Gerencial'), ('OLE', 'Operativo')], default='OLE', max_length=3),
        ),
    ]
