# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_users', '0006_profile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level_of_hierarchy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
