# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_users', '0007_auto_20180730_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
