# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0002_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_content.Lesson')),
                ('body', models.TextField()),
            ],
            bases=('learningco_content.lesson',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_content.Lesson')),
                ('body', models.TextField()),
            ],
            bases=('learningco_content.lesson',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_content.Lesson')),
                ('body', models.TextField()),
                ('video_url', embed_video.fields.EmbedVideoField()),
            ],
            bases=('learningco_content.lesson',),
        ),
    ]
