# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0003_intro_quiz_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_content.Lesson')),
                ('description', models.TextField()),
                ('body', models.TextField()),
            ],
            bases=('learningco_content.lesson',),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learningco_content.Quiz', verbose_name='Cuestionario')),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learningco_content.Skill', verbose_name='Competencia'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learningco_content.Question', verbose_name='Pregunta'),
        ),
    ]
