# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0003_auto_20180611_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='body',
            new_name='full_text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='full_text',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='body',
            new_name='description',
        ),
    ]
