# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0004_auto_20180529_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_content.Lesson')),
            ],
            bases=('learningco_content.lesson',),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learningco_content.ActivityList', verbose_name='Lista de actividades'),
        ),
    ]
