# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0005_auto_20180529_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('activity_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_list_bundles', to='learningco_content.ActivityList')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_bundles', to='learningco_content.Article')),
                ('intro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_bundles', to='learningco_content.Intro')),
                ('lessons', models.ManyToManyField(to='learningco_content.Lesson')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_bundles', to='learningco_content.Quiz')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_bundles', to='learningco_content.Video')),
            ],
        ),
    ]
