# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0006_auto_20180708_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='activity_list',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='video',
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
