# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0006_bundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylist',
            options={'ordering': ['name'], 'verbose_name': 'Leccion'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name'], 'verbose_name': 'Articulo'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'ordering': ['name'], 'verbose_name': 'Intro'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['name'], 'verbose_name': 'Lección'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['name'], 'verbose_name': 'Cuestionario'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['name'], 'verbose_name': 'Video'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='body',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='body',
        ),
        migrations.RemoveField(
            model_name='video',
            name='body',
        ),
        migrations.AddField(
            model_name='lesson',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
