# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0007_auto_20180709_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generation', models.CharField(choices=[('GZ', 'Generación Z'), ('GY', 'Millennial'), ('GX', 'Generación X'), ('BB', 'Baby Boomer'), ('GS', 'Generación Silenciosa')], default='GY', max_length=2)),
                ('level_of_hierarchy', models.CharField(choices=[('TLM', 'Directivo'), ('MLM', 'Gerencial'), ('OLE', 'Operativo')], default='OLE', max_length=3)),
                ('activity_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_list_bundles', to='learningco_content.ActivityList')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_bundles', to='learningco_content.Article')),
                ('intro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_bundles', to='learningco_content.Intro')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_bundles', to='learningco_content.Quiz')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='learningco_content.Skill', verbose_name='Competencia')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_bundles', to='learningco_content.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together=set([('skill', 'generation', 'level_of_hierarchy')]),
        ),
    ]
