# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 03:24
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(max_length=4, verbose_name='Código')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=10, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'carrier',
                'verbose_name_plural': 'carriers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Código')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sealedair_providers.Carrier', verbose_name='Carrier')),
            ],
            options={
                'verbose_name': 'camión',
                'verbose_name_plural': 'camiones',
                'ordering': ['code'],
            },
        ),
    ]
