# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['name'], 'verbose_name': 'carrier', 'verbose_name_plural': 'carriers'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['code'], 'verbose_name': 'camión', 'verbose_name_plural': 'camiones'},
        ),
    ]
