# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Código'),
        ),
    ]
