# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_users', '0004_profile_level_of_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='generation',
            field=models.CharField(choices=[('GZ', 'Generación Z'), ('GY', 'Millennial'), ('GX', 'Generación X'), ('BB', 'Baby Boomer'), ('GS', 'Generación Silenciosa')], default='GY', max_length=2),
        ),
    ]
