# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_users', '0005_auto_20180530_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
