# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_company', '0003_plant_transit_time_go'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='transit_time_go',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, verbose_name=''),
        ),
    ]
