# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_company', '0006_auto_20180914_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='transit_time_go',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Tiempo de tránsito (objetivo)'),
        ),
    ]
