# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sealedair_companies', '0002_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='human_resources',
            field=models.ManyToManyField(related_name='hr_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sealedair_companies.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='leaders',
            field=models.ManyToManyField(related_name='leader_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('0', 'No especificado'), ('A', '50-500 empleados'), ('B', '500-5,000 empleados'), ('C', '+5,000 empleados')], default='0', max_length=1),
        ),
    ]
