# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_companies', '0004_auto_20180427_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='company',
            name='human_resources',
            field=models.ManyToManyField(blank=True, related_name='hr_companies', to=settings.AUTH_USER_MODEL, verbose_name='Recursos humanos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sealedair_companies.Industry', verbose_name='Industria'),
        ),
        migrations.AlterField(
            model_name='company',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leader_companies', to=settings.AUTH_USER_MODEL, verbose_name='Líderes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('0', 'No especificado'), ('A', '50-500 empleados'), ('B', '500-5,000 empleados'), ('C', '+5,000 empleados')], default='0', max_length=1, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
