# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessoncompletion',
            old_name='leader_id',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='lessoncompletion',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
