# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_content', '0011_auto_20180709_1743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningco_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together=set([('lesson', 'leader')]),
        ),
        migrations.AlterUniqueTogether(
            name='skillcompletion',
            unique_together=set([('skill', 'leader')]),
        ),
    ]
