# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningco_content', '0006_bundle'),
        ('learningco_progress', '0003_skillcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningco_content.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningco_content.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCompletion',
            fields=[
                ('lessoncompletion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_progress.LessonCompletion')),
                ('quiz_score', models.IntegerField(default=0)),
            ],
            bases=('learningco_progress.lessoncompletion',),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz_completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningco_progress.QuizCompletion'),
        ),
    ]
