# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningco_progress', '0004_auto_20180605_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('lessoncompletion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learningco_progress.LessonCompletion')),
                ('file', models.FileField(blank=True, null=True, upload_to='activities')),
            ],
            bases=('learningco_progress.lessoncompletion',),
        ),
    ]
