# Generated by Django 2.1.2 on 2018-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_teams', '0001_initial'),
        ('publicomex_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owners',
            field=models.ManyToManyField(to='publicomex_teams.Team'),
        ),
    ]
