# Generated by Django 2.1.2 on 2018-10-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_core', '0001_initial'),
        ('publicomex_directory', '0002_category_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='zones',
            field=models.ManyToManyField(to='publicomex_core.Zone'),
        ),
    ]
