# Generated by Django 2.1.2 on 2018-10-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_teams', '0003_agency_business_firm_licensee_regionalmarketing'),
        ('publicomex_directory', '0003_category_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='publicomex_teams.Agency'),
        ),
    ]
