# Generated by Django 2.1.2 on 2018-10-04 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicomex_directory', '0004_category_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('file_type', models.CharField(choices=[('au', 'Audio'), ('vi', 'Video'), ('im', 'Imagen'), ('do', 'Documento')], default='im', max_length=2)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('image_file', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('other_file', models.FileField(null=True, upload_to='')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('expiration_date', models.DateField(null=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloads', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='publicomex_directory.Category')),
                ('files', models.ManyToManyField(to='publicomex_directory.File')),
            ],
        ),
    ]
