# Generated by Django 2.1.2 on 2018-10-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_directory', '0005_file_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('unit_of_length', models.CharField(choices=[('cm', 'Centimetros'), ('me', 'Metros')], default='cm', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publicomex_directory.Size'),
        ),
    ]
