# Generated by Django 2.1.2 on 2018-10-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicomex_directory', '0006_auto_20181004_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to='publicomex_directory.File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_downloads', to='publicomex_directory.File')),
            ],
        ),
    ]
