# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sealedair_companies', '0006_auto_20180606_0338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sealedair_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='sealedair_companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySkillScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sealedair_companies.Company')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sealedair_content.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderSkillQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sealedair_content.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderSkillScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField(default=0)),
                ('score_now', models.IntegerField(default=0)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lessons', models.ManyToManyField(to='sealedair_content.Lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sealedair_content.Skill')),
            ],
        ),
    ]
