# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_score', '0002_auto_20180712_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyscore',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_score', to='sealedair_companies.Company'),
        ),
    ]
