# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_score', '0004_trigger_signals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyskillscore',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_skill_scores', to='sealedair_companies.Company'),
        ),
    ]
