# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_score', '0005_auto_20180713_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderskillscore',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_skill_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
