# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set([('shipment', 'checkpoint')]),
        ),
    ]
