# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['start_datetime'], 'verbose_name': 'embarque', 'verbose_name_plural': 'embarques'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'estatus', 'verbose_name_plural': 'estatus'},
        ),
    ]
