# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0002_auto_20180731_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=50, verbose_name='Razón de retraso')),
            ],
            options={
                'verbose_name': 'Razón de retraso',
                'verbose_name_plural': 'Razones de retraso',
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('-start_datetime',), 'verbose_name': 'estatus', 'verbose_name_plural': 'estatus'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delay_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delay_reason_shipments', to='sealedair_shipments.DelayReason'),
        ),
    ]
