# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0003_auto_20180822_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delayreason',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='Razón de retraso'),
        ),
    ]
