# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0004_auto_20180823_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='checkpoint',
            field=models.CharField(choices=[('MTR', 'Tránsito MX'), ('MCA', 'Carrier MX'), ('BCR', 'En cruce'), ('BCA', 'Carrier US'), ('UTR', 'Tránsito US'), ('UDE', 'Entregado')], default='MTR', max_length=3, verbose_name='Checkpoint'),
        ),
    ]
