# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0005_auto_20180917_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cpm_number',
            field=models.CharField(default='', max_length=150, verbose_name='CPM number'),
        ),
    ]
