# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0006_shipment_cpm_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-datetime',), 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Salida'),
        ),
    ]
