# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0007_auto_20180925_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio'),
        ),
    ]
