# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_shipments', '0008_auto_20180925_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status_shipments', to='sealedair_shipments.Status', verbose_name='Estado actual'),
        ),
    ]
