# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sealedair_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['datetime'], 'verbose_name': 'notificacion', 'verbose_name_plural': 'notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='usernotificationsconfig',
            options={'verbose_name': 'Configuración de alertas', 'verbose_name_plural': 'Configuraciones de alertas'},
        ),
    ]
